### ISSUE TITLE
Docs do not specify a migrate step

### ISSUE THREAD

**Issue by RichardForshaw** [jamesturk/django-secretballot#24]
When I installed this I couldn't get it to work, as it was failing on an SQL error. After investigating I fixed the issue with a `manage.py migrate` which set up the necessary database tables.

This step isn't in the installation instructions, so should be added.

**Comment by jamesturk** [comment]
thanks for this, docs definitely need some attention, will work this in

**Comment by hedleyroos** [comment]
https://github.com/jamesturk/django-secretballot/pull/26
