### ISSUE TITLE
Likes for Users

### ISSUE THREAD

**Issue by fzdmd** [jamesturk/django-secretballot#25]
#models.py
import secretballot
from django.contrib.auth.models import User
secretballot.enable_voting_on(User)

All works fine.
By if I trying migrate db, i've got.
ValueError: Could not find manager VotableManager in secretballot.
Please note that you need to inherit from managers you dynamically generated with 'from_queryset()'.

**Comment by jamesturk** [comment]
Is this still an issue, can you provide a failing test?
