### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by MarinaaaniraM** [jamesturk/django-secretballot#27]
Hello!
In **_class Vote(models.Model)_** you have:

`    def __str__(self):
        return '{} from {} on {}'.format(self.get_vote_display(), self.token, self.content_object)`

Use, please `u'{} from {} on {}'` to correct utf-8 encoding, because you return **_self.content_object_** which can be in unicode.

**Comment by jamesturk** [comment]
Any chance you'd be able to provide an example of a failing test on this one?
