### ISSUE TITLE
setup.py does not install migrations

### ISSUE THREAD

**Issue by fabiommendes** [jamesturk/django-secretballot#33]
Setup.py do not install content in the secretballot.migrations package. This code fixes this:

```python
setup(
    ...
    package_dir={'secretballot': 'secretballot'},
    packages=['secretballot', 'secretballot.migrations'],
    package_data={
        'secretballot': [
            'migrations/*.*',
        ],
    },
    zip_safe=False,
    ...
)
```

zip_safe is necessary because migrations do not work properly on eggs.

**Comment by jamesturk** [comment]
can you check if the latest master branch fixes this, I think it will using find_packages instead of package_data- let me know if there are issues
