### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by Mazas17** [jamesturk/django-secretballot#34]
Getting issue when migrating everything in empty database. After command `manage.py migrate` getting error:

>   File "/home/mazvydas/Envs/fakelife_test/local/lib/python2.7/site-packages/django/db/models/manager.py", line 228, in all
>     return self.get_queryset()
>   **File "/home/mazvydas/Envs/fakelife_test/local/lib/python2.7/site-packages/secretballot/**init**.py", line 58, in get_queryset**
>     **content_type = ContentType.objects.get_for_model(self.model).id**
>   File "/home/mazvydas/Envs/fakelife_test/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 80, in get_for_model
>     "Error creating new content types. Please make sure contenttypes "
> RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.

I'm sure this is caused by `__init__.py` file trying to query `ContentType` which has been not migrated to database at the time.

Workaround was editing **init**.py file where it queries database

```
try:
    content_type = ContentType.objects.get_for_model(self.model).id
except:
    content_type = None
```

while migrating.

**Comment by jamesturk** [comment]
Just checking, is contenttypes in  your installed apps?

**Comment by Mazas17** [comment]
Yes. Tried to comment it out while migrating, but problem persisted.

**Comment by jamesturk** [comment]
is this with Django 1.10?

**Comment by Mazas17** [comment]
Django==1.8.14

**Comment by jamesturk** [comment]
OK thanks!

**Comment by jamesturk** [comment]
I haven't been able to reproduce this, any chance you'd be able to share a small sample that does this?

**Comment by jlmadurga** [comment]
We had same issue but is solved calling `secretballot.enable_voting_on` in our `AppConfig.ready` instead of in our `models.py`

**Comment by nick13jaremek** [comment]
We also ran into a similar issue: running any `python manage.py` command would raise a similar error as the one @Mazas17 has described, using `Django==1.8.16`. Here is the workaround we applied in case someone else stumbles on this kind of error.

**CONTEXT**
In our case, we did the following:
- Added the `secretballot.enable_voting_on(Person)` at the end of our `person_app/models.py` file, where the `Person` model is defined.
- Added a ManyToMany relationship with `Person` on another app's model, `Group`, located at `group_app/models.py`. The name of the m2m field was *people*.
- Added a `GroupAdminForm` class to `group_app/admin.py`
- Added a `GroupAdmin(admin.ModelAdmin)` class to `group_app/admin.py`, adding the *people* field in the list of `fields`.

```
# person_app/models.py 
class Person(models.Model):
      # Some fields

  secretballot.enable_voting_on(Person)
```


```
# group_app/models.py
class Group(models.Model):
      # Some fields
      people = models.ManyToManyField('person_app.Person',
                                           verbose_name=u"People",
                                           blank=True)
```

```
# group_app/admin.py
class GroupAdminForm(forms.ModelForm):
      class Meta:
            model = Group
            widgets = # list of widgets
            fields = '__all__'

class GroupAdmin(admin.ModelAdmin):
      list_display = ...
      fields = (..., 'people') # The m2m field

      filter_horizontal = ('people', )
```

** PROBLEM **
Then whenever we ran `python manage.py` in our repository **which did not have any migrations applied yet**, we got the following error:

```Traceback (most recent call last):
File "manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
utility.execute()
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 328, in execute
django.setup()
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
apps.populate(settings.INSTALLED_APPS)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
app_config.ready()
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
self.module.autodiscover()
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 24, in autodiscover
autodiscover_modules('admin', register_to=site)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
import_module('%s.%s' % (app_config.name, module_to_search))
File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
File "/home/rof/src/bitbucket.org/reclamador-es/reclamador-django/group_app/admin.py", line 8, in <module>
class GroupAdminForm(forms.ModelForm):
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/forms/models.py", line 285, in __new__
opts.help_texts, opts.error_messages)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/forms/models.py", line 212, in fields_for_model
formfield = f.formfield(**kwargs)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 2609, in formfield
'queryset': self.rel.to._default_manager.using(db),
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
return getattr(self.get_queryset(), name)(*args, **kwargs)
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/secretballot/__init__.py", line 59, in get_queryset
content_type = ContentType.objects.get_for_model(self.model).id
File "/home/rof/.virtualenv/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 80, in get_for_model
"Error creating new content types. Please make sure contenttypes "
RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.
```

**SOLUTION**
The workaround we applied was as follows:
- Remove the `secretballot.enable_voting_on(Person)` line from `person_app/models.py`.
- Create a file called `apps.py` in the `person_app` directory.
- Inside the file `apps.py`, add the following lines of code:

```
# -*- coding: utf-8 -*-
from django.apps import AppConfig
from django.apps import apps

import secretballot

class PersonAppConfig(AppConfig):
    name = 'person_app'
    verbose_name = "People"

    def ready(self):
        person_model = apps.get_model("person_app", "Person")
        secretballot.enable_voting_on(person_model)
```

And, in the `person_app/__init__.py` file, we added the following lines:
```
# -*- coding: utf-8 -*-
default_app_config = "person_app.apps.PersonAppConfig"
```

Finally, the `ContentType` error was gone and we were able to execute any `python manage.py` command successfully.

The purpose was to delay loading the secretballot `VotingManager` until the `person_app` was ready.

Hope this helps!

**Comment by jamesturk** [comment]
thanks, this solution is now noted in the README and is the recommended way to enable voting
