### ISSUE TITLE
Clearing old votes

### ISSUE THREAD

**Issue by alastc** [jamesturk/django-secretballot#37]
I've been using secretballot very happily for several years to run a 'windsurfer of the year' vote, this year I'm getting a few reports that some people are being told they have voted, when they haven't - since last year.

I have no means of knowing if someone else on the same IP address had already voted, it is possible but they claim that no one else voted from their location.

Is it possible that they are still blocked by having done last years vote? If so, is there a means of removing all the previous votes? (Or at least the old IP addresses from previous years).

I was checking the documentation for a management command or similar, but I couldn't see anything.

Thanks,

-Alastair

**Comment by jamesturk** [comment]
The specifics here would depend a lot on your particular set up so it'd be
hard to say for sure what is happening (IP or previous year's votes).

If you want to wipe all votes you can just do it in ./manage.py shell or
dbshell by doing a query on vote objects attached to the old objects- that
should allow new votes to be cast

On Wed, Dec 14, 2016 at 4:25 PM, Alastair Campbell <notifications@github.com

**Comment by alastc** [comment]
Ah, each of my candidates has a year (in the model), so presumably I can create a query for all previous years and delete votes attached.

Ok, thanks, I'll try that.
