### ISSUE TITLE
Release latest changes to PyPi

### ISSUE THREAD

**Issue by phala** [jamesturk/django-secretballot#44]
Following the latest changes, can you please release a new version to PyPi @jamesturk?

**Comment by phala** [comment]
Hey @jamesturk. Any updates on that new release?

**Comment by jamesturk** [comment]
it'll probably be a little bit before I get to this

**Comment by phala** [comment]
@jamesturk if you could please get to this as soon as you can. It is a bit of an emergency...

**Comment by jamesturk** [comment]
0.7.0 is released
